export const CHANGE_SUBREDDIT = 'CHANGE_SUBREDDIT';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';